name: "Tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.2, 8.1 ]
        laravel: [ 10, 9 ]
        stability: [ prefer-lowest, prefer-stable ]
        include:
          - laravel: ^10.0
            testbench: ^8.0
            carbon: ^2.63
          - laravel: ^9.0
            testbench: ^7.0
            carbon: ^2.63

    name: "PHP: v${{ matrix.php }} / Laravel: v${{ matrix.laravel }} - ${{ matrix.stability }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: xdebug

      - name: Install Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nesbot/carbon:${{ matrix.carbon }}" --no-interaction --no-update --optimize-autoloader
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Run Tests
        run: vendor/bin/pest
