name: "Run Tests"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - *

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2, 8.1 ] # Add/Remove PHP versions here
        laravel: [ 10, 9 ] # Add/Remove Laravel versions here
        stability: [ prefer-lowest, prefer-stable ]

    name: "PHP: v${{ matrix.php }} / Laravel: v${{ matrix.laravel }} - ${{ matrix.stability }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Update Dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Run Tests
        run: vendor/bin/pest
